# Change these first
owner: Entropy-rgb # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
workflowSchedule:
  uptime: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"        # Runs the status checks every 5 minutes
  status-website: "0 0 * * *" # Rebuilds the status website once a day
sites:
  - name: BoloDB
    url: https://bolodb.dev
assignees:
  - Entropy-rgb
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bolodb.dev
  themeUrl: https://status.bolodb.dev/linear-theme.css
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**BoloDB** is an app to query your database in Natural language."
  introMessage: This is the status/uptime of the service BoloDB
  navbar:
    - title: Status
      href: /
    - title: BoloDB
      href: https://bolodb.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
